### PR TITLE
Add launcher to the web

### PR DESCRIPTION
**Pull request by likeawindrammer**

### CODE REVIEW

**Comment by stonedDiscord** [comment]
add thumbs.db in general to gitignore

can you pls fix the 7zip box on the faq, one of them uses the wrong toggle id

**Comment by likeawindrammer** [comment]
I did the first, but the second should be already fixed. The website currently opens every section of the FAQ correctly, including "How do I open ZIP or RAR files?"
There was an issue with that one before the release of 2.6.2, but AFAIK got fixed once the website was updated since it got this commit too https://github.com/AttorneyOnline/website/commit/f8ce09213b0096d54889b4e63fa356e7ba73be3f
Don't know if you mean some other issue I haven't noticed yet.

**Comment by likeawindrammer** [comment]
> talbe

shit, oh well
how this looks: https://youtu.be/piHf_G-I1Nk

**Comment by likeawindrammer** [comment]
https://youtu.be/piHf_G-I1Nk

**Pull request closed without merging**
